# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI_Weather_Station_Without_Container.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 181, 134))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutWeatherStation = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutWeatherStation.setContentsMargins(0, 0, 0, 0)
        self.layoutWeatherStation.setObjectName("layoutWeatherStation")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.layoutWeatherStation.addWidget(self.label)
        self.btnCollectOn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnCollectOn.setObjectName("btnCollectOn")
        self.layoutWeatherStation.addWidget(self.btnCollectOn)
        self.btnCollectOff = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnCollectOff.setObjectName("btnCollectOff")
        self.layoutWeatherStation.addWidget(self.btnCollectOff)
        self.lblInterval = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblInterval.setObjectName("lblInterval")
        self.layoutWeatherStation.addWidget(self.lblInterval)
        self.dbmInterval = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.dbmInterval.setMinimum(1)
        self.dbmInterval.setMaximum(60)
        self.dbmInterval.setProperty("value", 5)
        self.dbmInterval.setObjectName("dbmInterval")
        self.layoutWeatherStation.addWidget(self.dbmInterval)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 340, 172, 73))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.layoutLCD = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.layoutLCD.setContentsMargins(0, 0, 0, 0)
        self.layoutLCD.setObjectName("layoutLCD")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.layoutLCD.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lcdHumidity = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdHumidity.setObjectName("lcdHumidity")
        self.layoutLCD.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcdHumidity)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.layoutLCD.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lcdTemperature = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdTemperature.setObjectName("lcdTemperature")
        self.layoutLCD.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lcdTemperature)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(40, 220, 197, 81))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.layoutDebug = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.layoutDebug.setContentsMargins(0, 0, 0, 0)
        self.layoutDebug.setObjectName("layoutDebug")
        self.checkDebug = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.checkDebug.setObjectName("checkDebug")
        self.layoutDebug.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkDebug)
        self.lblOnOff = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lblOnOff.setObjectName("lblOnOff")
        self.layoutDebug.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblOnOff)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.layoutDebug.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dbmTemperature = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.dbmTemperature.setObjectName("dbmTemperature")
        self.layoutDebug.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dbmTemperature)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.layoutDebug.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dbmHumidity = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.dbmHumidity.setObjectName("dbmHumidity")
        self.layoutDebug.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dbmHumidity)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Start collecting weather information:"))
        self.btnCollectOn.setText(_translate("MainWindow", "Turn on Weather Station"))
        self.btnCollectOff.setText(_translate("MainWindow", "Turn off Weather Station"))
        self.lblInterval.setText(_translate("MainWindow", "Refresh interval (seconds)"))
        self.label_5.setText(_translate("MainWindow", "Current Humidity"))
        self.label_2.setText(_translate("MainWindow", "Current temperature"))
        self.checkDebug.setText(_translate("MainWindow", "DebugMode"))
        self.lblOnOff.setText(_translate("MainWindow", "On / Off"))
        self.label_3.setText(_translate("MainWindow", "(Debug) Change temperature: "))
        self.label_4.setText(_translate("MainWindow", "(Debug) Change Humidity"))

