# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI_Weather_Station2.0.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 237)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(260, 120, 172, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.layoutLCD = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.layoutLCD.setContentsMargins(0, 0, 0, 0)
        self.layoutLCD.setObjectName("layoutLCD")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.layoutLCD.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lcdHumidity = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdHumidity.setObjectName("lcdHumidity")
        self.layoutLCD.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcdHumidity)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.layoutLCD.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lcdTemperature = QtWidgets.QLCDNumber(self.formLayoutWidget)
        self.lcdTemperature.setObjectName("lcdTemperature")
        self.layoutLCD.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lcdTemperature)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(260, 20, 228, 71))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.layoutDebug = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.layoutDebug.setContentsMargins(0, 0, 0, 0)
        self.layoutDebug.setObjectName("layoutDebug")
        self.checkDebug = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.checkDebug.setObjectName("checkDebug")
        self.layoutDebug.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkDebug)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.layoutDebug.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dbmTemperature = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.dbmTemperature.setObjectName("dbmTemperature")
        self.layoutDebug.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dbmTemperature)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.layoutDebug.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dbmHumidity = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.dbmHumidity.setObjectName("dbmHumidity")
        self.layoutDebug.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dbmHumidity)
        self.columnView = QtWidgets.QColumnView(self.centralwidget)
        self.columnView.setGeometry(QtCore.QRect(10, 30, 231, 131))
        self.columnView.setObjectName("columnView")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 40, 216, 111))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.btnCollectOn = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.btnCollectOn.setObjectName("btnCollectOn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.btnCollectOn)
        self.btnCollectOff = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.btnCollectOff.setObjectName("btnCollectOff")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.btnCollectOff)
        self.lblInterval = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lblInterval.setObjectName("lblInterval")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblInterval)
        self.dbmInterval = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.dbmInterval.setMinimum(1)
        self.dbmInterval.setMaximum(60)
        self.dbmInterval.setProperty("value", 5)
        self.dbmInterval.setObjectName("dbmInterval")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dbmInterval)
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(250, 10, 251, 91))
        self.listView.setObjectName("listView")
        self.listView_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(250, 110, 191, 71))
        self.listView_2.setObjectName("listView_2")
        self.listView_2.raise_()
        self.listView.raise_()
        self.columnView.raise_()
        self.formLayoutWidget.raise_()
        self.formLayoutWidget_2.raise_()
        self.formLayoutWidget_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Weather Station"))
        self.label_5.setText(_translate("MainWindow", "Current Humidity"))
        self.label_2.setText(_translate("MainWindow", "Current Temperature"))
        self.checkDebug.setText(_translate("MainWindow", "DebugMode"))
        self.label_3.setText(_translate("MainWindow", "(Debug) Change Temperature: "))
        self.label_4.setText(_translate("MainWindow", "(Debug) Change Humidity"))
        self.label.setText(_translate("MainWindow", "WeatherStation"))
        self.btnCollectOn.setText(_translate("MainWindow", "Turn on Weather Station"))
        self.btnCollectOff.setText(_translate("MainWindow", "Turn off Weather Station"))
        self.lblInterval.setText(_translate("MainWindow", "Refresh interval (Seconds):"))

