# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI_Weather_Station2.3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 433)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(340, 20, 291, 101))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.layoutDebug = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.layoutDebug.setContentsMargins(0, 0, 0, 0)
        self.layoutDebug.setObjectName("layoutDebug")
        self.dbmHumidity = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.dbmHumidity.setObjectName("dbmHumidity")
        self.layoutDebug.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dbmHumidity)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.layoutDebug.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dbmTemperature = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.dbmTemperature.setObjectName("dbmTemperature")
        self.layoutDebug.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dbmTemperature)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.layoutDebug.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lblOnOff = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lblOnOff.setObjectName("lblOnOff")
        self.layoutDebug.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblOnOff)
        self.checkDebug = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.checkDebug.setObjectName("checkDebug")
        self.layoutDebug.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkDebug)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.layoutDebug.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.columnView = QtWidgets.QColumnView(self.centralwidget)
        self.columnView.setGeometry(QtCore.QRect(10, 10, 311, 131))
        self.columnView.setObjectName("columnView")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(30, 20, 269, 111))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.dbmInterval = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.dbmInterval.setMinimum(1)
        self.dbmInterval.setMaximum(60)
        self.dbmInterval.setProperty("value", 5)
        self.dbmInterval.setObjectName("dbmInterval")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dbmInterval)
        self.lblInterval = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lblInterval.setObjectName("lblInterval")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblInterval)
        self.btnCollectOff = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.btnCollectOff.setObjectName("btnCollectOff")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnCollectOff)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.btnCollectOn = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.btnCollectOn.setObjectName("btnCollectOn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnCollectOn)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(330, 10, 311, 131))
        self.listView.setObjectName("listView")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 160, 271, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lcdTemperature = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lcdTemperature.setFont(font)
        self.lcdTemperature.setObjectName("lcdTemperature")
        self.verticalLayout.addWidget(self.lcdTemperature)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lcdHumidity = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lcdHumidity.setFont(font)
        self.lcdHumidity.setObjectName("lcdHumidity")
        self.verticalLayout.addWidget(self.lcdHumidity)
        self.listView_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(170, 150, 311, 192))
        self.listView_2.setObjectName("listView_2")
        self.listView_2.raise_()
        self.listView.raise_()
        self.columnView.raise_()
        self.formLayoutWidget_2.raise_()
        self.formLayoutWidget_3.raise_()
        self.verticalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Weather Station"))
        self.label_4.setText(_translate("MainWindow", "(Debug) Change Humidity"))
        self.label_3.setText(_translate("MainWindow", "(Debug) Change temperature: "))
        self.lblOnOff.setText(_translate("MainWindow", "On / Off"))
        self.checkDebug.setText(_translate("MainWindow", "DebugMode"))
        self.label_8.setText(_translate("MainWindow", "Debug Controller"))
        self.lblInterval.setText(_translate("MainWindow", "Refresh interval (Seconds):"))
        self.btnCollectOff.setText(_translate("MainWindow", "Off"))
        self.label_6.setText(_translate("MainWindow", "Weather Station status:"))
        self.btnCollectOn.setText(_translate("MainWindow", "On"))
        self.label.setText(_translate("MainWindow", "Weather Station status:"))
        self.label_7.setText(_translate("MainWindow", "Weather Station Controller"))
        self.label_9.setText(_translate("MainWindow", "Information HUD"))
        self.label_2.setText(_translate("MainWindow", "Current temperature"))
        self.label_5.setText(_translate("MainWindow", "Current Humidity"))

